new deliver config

diff --git a/.deliver/config b/.deliver/config
--- a/.deliver/config
+++ b/.deliver/config
@@ -1,67 +1,90 @@
-#!/bin/bash
-
 APP="fkc_elixir"
 
 BUILD_HOST="65.20.77.43"
 BUILD_USER="ravi"
-BUILD_AT="/tmp/edeliver/${APP}/builds"
+BUILD_AT="/tmp/edeliver/$APP/builds"
 
-START_DEPLOY=true
-CLEAN_DEPLOY=true
+RELEASE_DIR="/tmp/edeliver/$APP/builds/_build/prod/rel/$APP"
 
 # prevent re-installing node modules; this defaults to "."
 GIT_CLEAN_PATHS="_build rel priv/static"
 
+# STAGING_HOSTS="65.20.77.43"
+# STAGING_USER="ravi"
+# TEST_AT="/home/ravi/staging"
+
 PRODUCTION_HOSTS="65.20.77.43"
 PRODUCTION_USER="ravi"
-DELIVER_TO="/home/ravi/apps"
-AUTO_VERSION=revision
+DELIVER_TO="/home/ravi"
 
-# For Phoenix projects, symlink prod.secret.exs to our tmp source
+# For *Phoenix* projects, symlink prod.secret.exs to our tmp source
 pre_erlang_get_and_update_deps() {
-  local _prod_secret_path="/home/ravi/apps/${APP}/secret/prod.secret.exs"
+  local _prod_secret_path="/home/deploy/prod.secret.exs"
   if [ "$TARGET_MIX_ENV" = "prod" ]; then
-    status "Linking '$_prod_secret_path'"
     __sync_remote "
-      [ -f ~/.profile ] && source ~/.profile
-      mkdir -p '$BUILD_AT'
-      ln -sfn '$_prod_secret_path' '${BUILD_AT}/config/prod.secret.exs'
+      ln -sfn '$_prod_secret_path' '$BUILD_AT/config/prod.secret.exs'
     "
   fi
 }
 
+# pre_erlang_clean_compile() {
+#   status "Running phoenix.digest" # log output prepended with "----->"
+#     __sync_remote " # runs the commands on the build host
+#       # load profile (optional)
+#       [ -f ~/.profile ] && source ~/.profile 
+#       set -e # fail if any command fails (recommended)
+#       cd '$BUILD_AT' # enter the build directory on the build host (required)
+#       mkdir -p priv/static # required by the phoenix.digest task
+#       npm install 
+
+
+#       # run your custom task
+#       APP='$APP' MIX_ENV='$TARGET_MIX_ENV' $MIX_CMD phoenix.digest $SILENCE
+#     "
+# }
+
 pre_erlang_clean_compile() {
-  status "Running npm install"
-    __sync_remote "
-      [ -f ~/.profile ] && source ~/.profile
-      set -e
-      cd '${BUILD_AT}/assets'
-      npm install
-    "
+  status "Installing NPM dependencies"
+  __sync_remote "
+    [ -f ~/.profile ] && source ~/.profile
+    set -e
+    cd '$BUILD_AT'
+    npm install --prefix ./assets $SILENCE
+  "
 
-  # status "Compiling assets"
-  #   __sync_remote "
-  #     [ -f ~/.profile ] && source ~/.profile
-  #     set -e
-  #     cd '${BUILD_AT}/assets/node_modules/.bin/webpack --mode production --silent'
-  #   "
-
-  status "Running phoenix.digest" # log output prepended with 
+  status "Building static files"
   __sync_remote "
     [ -f ~/.profile ] && source ~/.profile
     set -e
     cd '$BUILD_AT'
     mkdir -p priv/static
-    APP='$APP' MIX_ENV='$TARGET_MIX_ENV' $MIX_CMD phx.digest $SILENCE
+    APP='$APP' MIX_ENV='$TARGET_MIX_ENV' $MIX_CMD esbuild default --minify $SILENCE
+  "
+
+  status "Running phx.digest.clean"
+  __sync_remote "
+    [ -f ~/.profile ] && source ~/.profile
+    set -e
+    cd '$BUILD_AT'
     APP='$APP' MIX_ENV='$TARGET_MIX_ENV' $MIX_CMD phx.digest.clean $SILENCE
+  "
+
+  status "Running phx.digest"
+  __sync_remote "
+    [ -f ~/.profile ] && source ~/.profile
+    set -e
+    cd '$BUILD_AT'
+    APP='$APP' MIX_ENV='$TARGET_MIX_ENV' $MIX_CMD phx.digest $SILENCE
   "
 }
 
-# post_extract_release_archive() {
-#   status "Removing start_erl.data if it exists"
-#   __remote "
-#     [ -f ~/.profile ] && source ~/.profile
-#     cd $DELIVER_TO/$APP/var $SILENCE
-#     rm start_erl.data
-#   "
-# }
+post_extract_release_archive() {
+  status "Removing release version start_erl.data file"
+  __sync_remote "
+    [ -f ~/.profile ] && source ~/.profile
+    set -e
+    if [ -f /home/ravi/fkc_elixir/fkc_elixir/var/start_erl.data ]; then
+      rm /home/ravi/fkc_elixir/fkc_elixir/var/start_erl.data
+    fi
+  "
+}
